### ISSUE TITLE
PostgresSQL usando código do MSSQL

### ISSUE THREAD

**Issue by dotHunter** [Acrisio-Filho/SuperSS-Dev#10]
Os códigos de conexão da base do Postgresql estão se conectando à base MSSQL

**postgresql.cpp**
![image](https://user-images.githubusercontent.com/21126910/139927615-b6a5cb9c-edc8-4326-80b9-0936f4675749.png)

**mssql.cpp**
![image](https://user-images.githubusercontent.com/21126910/139927672-2035d625-927e-4cad-9a1b-fed02a314956.png)

O resultado é que quando se executa o server,mesmo com um banco postgresql o server fica com erro,pois tenta se conectar via odbc ao sql server

![image](https://user-images.githubusercontent.com/21126910/139927941-bdc3f4c4-d7a3-473d-ab49-85e3fbdd7892.png)

**OBS : Obrigado pelo codigo fonte e pelos esforços!**

**Comment by vitinhonunes** [comment]
Consegue enviar uma correção para o acrisio ? Ou aqui mesmo ?

**Comment by Acrisio-Filho** [comment]
Procura no Google odbc driver para o postgresSQL
