### ISSUE TITLE
ProjectG and possible release builds 

### ISSUE THREAD

**Issue by diosn** [Acrisio-Filho/SuperSS-Dev#11]
Hello @Acrisio-Filho , I hope you are okay.

First of all, thank you so much for publishing this source code to the community.

What you're doing is really a great work.

Could you please attach to the source the original client ProjectG.exe and its versions (I assume it is from Pangya Japan version 983 up to 987~) including possible builds of the projectg with and without gameguard.

Also, would it be possible for you to include a release build of this code source? It would help people like me that don't have skills to properly compile it. And how do you compile the gameguard by yourself? Could you share you work?

My intention is to mod the japanese client to english in all it's ways, including translating all original Description.iff items from Japan.

Anyway, thanks for your attention.

//

Olá @Acrisio-Filho , espero que esteja bem.

Primeiro de tudo, muito obrigado por todo o seu trabalho apesar da comunidade Pangya estar fraca e praticamente morta por conta dos desenvolvedores originais.

Seu trabalho é excelente. 

Você poderia por favor colocar as versões ProjectG que tiver, que assumo que são do Pangya JP entre 983~987, inclusive se tiver alguma modificada com e sem gameguard? E a modificação da gameguard, como você encripta ela? Só tenho consigo encontrar o decryptor.

Seria possível também disponibilizar um release 'limpo' da source? Nem todos, incluindo eu, tem habilidades para poder compilar uma build.

Minha intenção é modificar o cliente japonês para o inglês para intacto, um projeto que tenho em mente há bastante tempo, porém que depende de servidor. 

De todo modo, obrigado por sua atenção.

**Comment by Acrisio-Filho** [comment]
Sorry I can't help you, ask God he's the only one who can help you.
