### ISSUE TITLE
problemas com lzPak

### ISSUE THREAD

**Issue by luismk** [Acrisio-Filho/SuperSS-Dev#17]
![image](https://github.com/user-attachments/assets/2366501e-1384-499b-b09e-4f6482122ccb)

codigo em si funciona totalmente 

porem quando se tenta criar um pak, o codigo não consegue lidar com pasta
corrigir o problema com '/' 
isso fazia parece outras coisas na pasta sem ter nada haver

**Comment by Acrisio-Filho** [comment]
Esse problema você contorna usando o endereço completo da pasta ou o relativo com "./". Depois eu faço uma correção no código.

Ex:
lzpak.exe C:/pasta/pasta
lzpak.exe /home/pasta
lzpak.exe ./pasta

**Comment by Acrisio-Filho** [comment]
Correção feita no código
