### ISSUE TITLE
Problemas/Bugs com [Same_ID_Login]

### ISSUE THREAD

**Issue by luismk** [Acrisio-Filho/SuperSS-Dev#19]
se possivel crie uma função no game server 

onde bloquei o jogador em casos de  [Same_ID_Login] ativo  ou não permita ele jogar em algumas situações

Bugs: 

por exemplo se voce logar com mesma conta no servidor

e ir tentar jogar no memorial por exemplo
 ele vai poder jogar em ambas contas com mesmas moedas, pois o servidor não conseguir lidar com isso

enquanto uma conta esta consumindo o itens, a outra esta rodando as coins

gerando um 'bug' pelo same_id_login ativo

**Comment by Acrisio-Filho** [comment]
Essa função do mesmo id é para testes, isso nunca que deve ser ativo.
